const API_BASE="https://api.schedulemp.site";
const state={servers:[],favorites:new Set(JSON.parse(localStorage.getItem("schedulemp:favorites")||"[]")),ascending:false};
const $=q=>document.querySelector(q),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
if(new URLSearchParams(location.search).get("desktop")==="1")document.querySelectorAll(".web-link").forEach(link=>{link.target="_blank";link.rel="noopener noreferrer"});
function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),2600)}
function queryTokens(value){const phrase=(value.match(/"([^"]+)"/)||[])[1];const tag=(value.match(/(?:^|\s)tag:([^\s]+)/i)||[])[1];const region=(value.match(/(?:^|\s)region:([^\s]+)/i)||[])[1];const plain=value.replace(/"[^"]+"|(?:^|\s)(?:tag|region):[^\s]+/gi," ").trim();return{phrase,tag,region,plain}}
function matches(server,value){const q=queryTokens(value);const hay=[server.name,server.description,server.map,server.mode,...(server.tags||[])].join(" ").toLowerCase();return(!q.phrase||hay.includes(q.phrase.toLowerCase()))&&(!q.tag||(server.tags||[]).some(t=>t.toLowerCase().includes(q.tag.toLowerCase())))&&(!q.region||(server.region||"").toLowerCase().includes(q.region.toLowerCase()))&&(!q.plain||hay.includes(q.plain.toLowerCase()))}
function serverRow(server){const tags=[...(server.tags||[]),server.passworded&&"PASSWORD",server.whitelisted&&"WHITELIST",server.queue>0&&`QUEUE ${server.queue}`].filter(Boolean);return `<article class="server" data-id="${esc(server.id)}"><div class="server-icon">S</div><div><h3>${esc(server.name)}</h3><p>${esc(server.description||`${server.map} · ${server.mode}`)}</p><div class="server-tags">${tags.map(esc).join("  ●  ")}</div></div><div class="population"><strong>${server.players}/${server.maxPlayers}</strong><span>players</span></div><div class="peak"><strong>${server.peak24h??server.players}</strong><span>peak (24h)</span></div><button class="favorite ${state.favorites.has(server.id)?"on":""}" aria-label="Favorite ${esc(server.name)}">★</button><button class="join">CONNECT</button></article>`}
function featuredRow(server){return `<article class="featured" data-id="${esc(server.id)}"><div class="server-icon">S</div><div><h4>${esc(server.name)}</h4><p>${esc((server.tags||[]).join(" ● ")||server.description)}</p></div><div class="featured-count">${server.players}/${server.maxPlayers}<small>${server.peak24h??server.players} peak</small></div></article>`}
function render(){const query=$("#search").value,region=$("#region").value,hideFull=$("#hide-full").checked,hidePassworded=$("#hide-passworded").checked;let servers=state.servers.filter(s=>matches(s,query)).filter(s=>!region||s.region===region).filter(s=>!hideFull||s.players<s.maxPlayers).filter(s=>!hidePassworded||!s.passworded).sort((a,b)=>(state.ascending?1:-1)*(a.players-b.players)||a.name.localeCompare(b.name));$("#server-count").textContent=`${servers.length} ONLINE`;$("#server-list").innerHTML=servers.length?servers.map(serverRow).join(""):`<div class="empty"><div><strong>No servers found</strong>Try a different search or check back shortly.</div></div>`;const featured=[...state.servers].sort((a,b)=>b.players-a.players).slice(0,12);$("#featured-list").innerHTML=featured.length?featured.map(featuredRow).join(""):`<div class="empty" style="min-height:300px"><div><strong>No featured servers</strong>Online servers will appear here.</div></div>`}
async function refresh(){try{const response=await fetch(`${API_BASE}/api/v1/servers`);if(!response.ok)throw new Error(`Server list returned ${response.status}`);state.servers=(await response.json()).servers;const selected=$("#region").value,regions=[...new Set(state.servers.map(s=>s.region).filter(Boolean))].sort();$("#region").innerHTML='<option value="">All regions</option>'+regions.map(r=>`<option>${esc(r)}</option>`).join("");$("#region").value=selected;render()}catch(error){toast("Server list is not online yet");render()}}
function connect(server,password=""){const payload=btoa(JSON.stringify({id:server.id,host:server.host,port:server.port,password}));location.href=`schedulemp://connect?payload=${encodeURIComponent(payload)}`;toast(`Opening ${server.name}`)}
document.addEventListener("click",event=>{const row=event.target.closest("[data-id]");if(row){const server=state.servers.find(s=>s.id===row.dataset.id);if(server&&event.target.closest(".favorite")){state.favorites.has(server.id)?state.favorites.delete(server.id):state.favorites.add(server.id);localStorage.setItem("schedulemp:favorites",JSON.stringify([...state.favorites]));render();return}if(server&&(event.target.closest(".join")||event.target.closest(".featured")))connect(server)} });
$("#filters-button").onclick=()=>{$("#filter-panel").hidden=!$("#filter-panel").hidden};$("#sort-button").onclick=()=>{state.ascending=!state.ascending;render()};$("#direct-button").onclick=()=>$("#direct-dialog").showModal();$("#clear-search").onclick=()=>{$("#search").value="";render()};$("#direct-form").addEventListener("submit",event=>{if(event.submitter?.value==="cancel")return;event.preventDefault();const host=$("#direct-host").value.trim(),port=Number($("#direct-port").value);if(!host||port<1||port>65535)return toast("Enter a valid server address and port");connect({id:`direct:${host}:${port}`,name:host,host,port},$("#direct-password").value);$("#direct-dialog").close()});["#search","#region","#hide-full","#hide-passworded"].forEach(q=>$(q).addEventListener("input",render));refresh();setInterval(refresh,30000);
